- - - 
### Contenido
* *Bibliotecas (library): numpy *
- - -

### numpy: python numerico

In [1]:
import numpy as np

In [2]:
np.pi

3.141592653589793

In [3]:
pi

NameError: name 'pi' is not defined

In [4]:
from numpy import pi

In [5]:
pi

3.141592653589793

** Ejercicio.** Escribe una función que calcule el volumen de una esfera 
al dar como argumento el radio.

In [7]:
from numpy import *

In [10]:
cos(pi)

-1.0

**Un poco de color con markdown language**

`<font color=blue>Azul</font>`

### <font color=blue>Vectores y operaciones con vectores</font>

In [11]:
a = np.array( [1,2,-1,100] )

In [13]:
a.dtype

dtype('int64')

In [19]:
b = np.zeros(10)
print (b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
b.dtype

dtype('float64')

In [ ]:
a = np.arange(0.,10.,0.1)

In [ ]:
print (a)

In [21]:
l = np.linspace(0,10,101)

In [22]:
print (l)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3
  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7
  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1
  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1  5.2  5.3  5.4  5.5
  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5  6.6  6.7  6.8  6.9
  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9  8.   8.1  8.2  8.3
  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3  9.4  9.5  9.6  9.7
  9.8  9.9 10. ]


In [24]:
a = np.array( [1., 4., 7. ])
b = np.array( [1., 2., -2. ])

In [26]:
print (a+b)
print (a-b)
print (a*b)
print (a/b) 
print (a**b)

[2. 6. 5.]
[0. 2. 9.]
[  1.   8. -14.]
[ 1.   2.  -3.5]
[ 1.         16.          0.02040816]


**Ejercicio.** Crea un vector v con 100 entradas iguales a -3.

**Ejercicio.** Sumar los primeros 100 números enteros.

**Ejercicio.** Guardar en un arreglo 100 números aleatorios entre 0 y 1.

**Ejercicio.** Obtener el valor medio de 100 números aleatorios.

**Productos entre vectores**

In [28]:
np.dot(a,b)

-5.0

In [30]:
np.cross(a,b)

array([-22.,   9.,  -2.])

In [34]:
np.vdot(a,b)

(-5+0j)

In [40]:
a = np.array( [1J, 4., 7. ])
b = np.array( [1J, 2., -2. ])

In [41]:
np.dot(a,b)

(-7+0j)

In [42]:
np.vdot(a,b)

(-5+0j)

**función `np.conj( )`

In [43]:
np.dot( np.conj(a),b )

(-5+0j)

In [44]:
np.vdot(a,b)

(-5+0j)

**Funciones evaluadas en cada elemento de un vector**

In [45]:
def gauss(x):
    return 1./ (np.sqrt(2.)) * np.exp(-x*x / 2.)

In [47]:
gauss( np.linspace(-5,5) )

array([2.63514173e-06, 7.16007513e-06, 1.86613524e-05, 4.66531081e-05,
       1.11874210e-04, 2.57330532e-04, 5.67759729e-04, 1.20157196e-03,
       2.43919724e-03, 4.74958854e-03, 8.87109006e-03, 1.58931478e-02,
       2.73120809e-02, 4.50206323e-02, 7.11836617e-02, 1.07959532e-01,
       1.57055660e-01, 2.19158402e-01, 2.93342232e-01, 3.76619665e-01,
       4.63813437e-01, 5.47892800e-01, 6.20811558e-01, 6.74739177e-01,
       7.03435033e-01, 7.03435033e-01, 6.74739177e-01, 6.20811558e-01,
       5.47892800e-01, 4.63813437e-01, 3.76619665e-01, 2.93342232e-01,
       2.19158402e-01, 1.57055660e-01, 1.07959532e-01, 7.11836617e-02,
       4.50206323e-02, 2.73120809e-02, 1.58931478e-02, 8.87109006e-03,
       4.74958854e-03, 2.43919724e-03, 1.20157196e-03, 5.67759729e-04,
       2.57330532e-04, 1.11874210e-04, 4.66531081e-05, 1.86613524e-05,
       7.16007513e-06, 2.63514173e-06])

---
## ¡Alerta importante!
**Sobreescritura de valores**

In [48]:
a = np.array([0, 1, 2, 3])

In [49]:
print (a[0], a[2])

0 2


In [50]:
b = a[1:3]
print (b)

[1 2]


In [53]:
b[1] = 10 # b no es una copia es una 'vista'

In [54]:
a  # ¡también cambia!

array([ 0,  1, 10,  3])

In [55]:
# lo mismo pasa en las listas
l=[1,2,3]; k=l; k[1] = 10

In [56]:
l

[1, 10, 3]

--- 
## Matrices

In [71]:
M = np.array( [ [1, 2], [3, 4] ] )
print (M)

[[1 2]
 [3 4]]


In [72]:
B = np.array( [ [1, 2], [0, 1] ] )

In [73]:
B

array([[1, 2],
       [0, 1]])

In [74]:
M*B

array([[1, 4],
       [0, 4]])

In [75]:
np.dot(M,B)

array([[ 1,  4],
       [ 3, 10]])

**Cambiar forma de una matriz**

In [77]:
M.shape

(2, 2)

In [78]:
M.shape = (4, 1); print (M)

[[1]
 [2]
 [3]
 [4]]


In [79]:
M.reshape( 2, 2 )

array([[1, 2],
       [3, 4]])

**Operaciones comunes de una matriz**

In [82]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [83]:
np.arange(3)

array([0, 1, 2])

In [84]:
np.diag( np.arange(3) )

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

---
## Álgebra lineal

In [111]:
M = np.array( [[0.5, 0.5], [0.2, 0.8]] )
v = np.array([3, 5])

In [112]:
M

array([[0.5, 0.5],
       [0.2, 0.8]])

In [113]:
v

array([3, 5])

In [114]:
np.dot(M, v)

array([4. , 4.6])

In [115]:
np.dot(M,M)

array([[0.35, 0.65],
       [0.26, 0.74]])

**Ejercicio:** Utiliza el método de potencias para calcular el eigenvector de una matriz cuadrada $M$ correspondiente al eigenvalor de mayor módulo. Este método consiste en considerar la iteración $M^n \cdot v$.

In [124]:
v = np.array([-1,0]) 

In [125]:
for n in arange(100):
    v  = np.dot(M, v)/np.linalg.norm(np.dot(M, v))
print (v)

[-0.70710678 -0.70710678]


In [126]:
np.linalg.eig(M)[1]

array([[-0.92847669, -0.70710678],
       [ 0.37139068, -0.70710678]])

In [127]:
np.linalg.eig(M)[0]

array([0.3, 1. ])